#z
. ~/Repo/github/z/z.sh

#paths
export NODE_PATH=/usr/local/lib/node:$NODE_PATH
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/share/npm/bin:/Applications/MAMP/Library/bin:$PATH
export DOCROOT=/Users/dan/Sites
export CODEROOT=/Users/dan/Repo
export WORKON_HOME=$HOME/.virtualenvs

# aliases
alias e="mate"
alias g="gitx"
alias ll="ls -lsa"
alias gpu="git pull"
alias gp="git push"
alias gco="git commit -am"
alias ga="git add -A"
alias gs="git status"
alias zve="cd $VIRTUAL_ENV"

# ssh home router
alias router="ssh root@192.168.2.1"
alias huprouter="ssh root@192.168.2.1 'killall -1 dnsmasq'"

#virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

